application:
  host: 127.0.0.1
database:
  require_ssl: false

email_client:
  base_url: "https://api.postmarkapp.com"
  # Use the single sender email you authorised on Postmark!
  sender_email: "naravich@enres.co"
  authorization_token: "909a5191-0a12-4ce6-ba8a-9c0fa6ffae27"
